#!/usr/bin/perl -wT
# PingBack QueueManager
#
# Copyright (C) 2006 MichaelDaum@WikiRing.com
# All Rights Reserved. Foswiki Contributors are listed in
# the AUTHORS file in the root of this distribution.
# NOTE: Please extend that file, not this notice.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details, published at 
# http://www.gnu.org/copyleft/gpl.html
#
# This script is intended to be run as a cron job (remember it has to be run
# by a user who can write files created by the webserver user!)
# For example,
#
# 0 * * * * cd $FOSWIKI_ROOT/tools && perl ./pingbackmanager
#
BEGIN {
    unshift @INC, '.';
    require 'setlib.cfg';
}

use strict;
use Foswiki::Plugins::PingBackPlugin::QueueManager;
use Foswiki::UI;
Foswiki::UI::run(\&Foswiki::Plugins::PingBackPlugin::QueueManager::run);

1;

